#!/bin/sh

PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts"

# Path to the grpc_node_plugin
PROTOC_GEN_GRPC_PATH="./node_modules/.bin/grpc_tools_node_protoc_plugin"


find ./src/services -name "*.proto" -exec dirname {} \; | while read path; do
    # Generate Javascript code via grpc tools
		yarn run grpc_tools_node_protoc \
    --grpc_out=grpc_js:$path/types \
    --plugin=protoc-gen-grpc=$PROTOC_GEN_GRPC_PATH \
    --js_out=import_style=commonjs,binary:$path/types \
    -I $path $path/*.proto

    # Generate typescript type definitions
    yarn run grpc_tools_node_protoc \
    --plugin=protoc-gen-ts=$PROTOC_GEN_TS_PATH \
    --ts_out=$path/types \
    -I $path $path/*.proto

		ls $path/types/*_grpc_pb.d.ts

    # this is a hack until grpc-js get support for ts codegen
    # see: https://github.com/grpc/grpc-node/issues/1417
		# Fix import paths within TypeScript files generated by `grpc_tools_node_protoc`
    sed -i "" -e "s/from \"grpc\"/from \"@grpc\/grpc-js\"/g" $path/types/*_grpc_pb.d.ts
done

# The generated file src/services/storage/types/service_grpc_pb.d.ts does not work.
# Fixed by remplacing this file by a manually created file.
cp src/services/storage/service_grpc_pb.d._ts src/services/storage/types/service_grpc_pb.d.ts

echo "Done"